### ISSUE TITLE
Update OpenAI configuration to support custom models

### ISSUE THREAD

**Issue by desprit** [desprit/tg-ai-connector#11]
OpenAI integration is currently fixed on davinci model. Text completion API should be separated from chat API and configurable from configuration.

**Comment by desprit** [comment]
Updated section of the configuration:
```toml
[integrations.openai]
api_key = "OPEN_AI_TOKEN" # set it to enable OpenAI integration
[[integrations.openai.networks]]
name = "completion"
version = "text-davinci-003"
command = "t" # Telegram command to trigger Text Completion requests
[[integrations.openai.networks]]
name = "chat"
version = "gpt-4"
command = "c" # Telegram command to trigger ChatGPT requests
[[integrations.openai.networks]]
name = "image"
version = "dalle"
command = "d" # Telegram command to trigger Dall-E requests
```

Text Completion and Chat are now separate handlers. It's also possible to select the network.
